
import javax.swing.table.TableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Bookings extends javax.swing.JFrame {

    /**
     * Creates new form Bookings
     */
    public Bookings() {
        initComponents();
        setTable();
    }
    
    
    DefaultTableModel model;
    
    // Method to populate the table with existing data
    public void setTable() {
        
        try (
             Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("SELECT booking_id, event, number_of_slots, phone_number, email, status FROM Booking");
             ResultSet rs = pst.executeQuery()) {
            
            while (rs.next()) {
                String bookingId = rs.getString("booking_id");
                String event = rs.getString("event");
                String slots = rs.getString("number_of_slots");
                String phoneNumber = rs.getString("phone_number");
                String email = rs.getString("email");
                String status = rs.getString("status");

                 Object[] obj = {bookingId, event, slots, phoneNumber, email, status};
                model = (DefaultTableModel)packageTbl.getModel();
                model.addRow(obj); 
            
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
      // Method to add a new booking
    public void addBooking() {
        String event = eventTx.getText();
        int slots = Integer.parseInt(slotsTx.getText());
        String phoneNumber = numberTx.getText();
        String email = emailTX.getText();

        try (Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("INSERT INTO Booking (event, number_of_slots, phone_number, email) VALUES (?, ?, ?, ?)")) {

            pst.setString(1, event);
            pst.setInt(2, slots);
            pst.setString(3, phoneNumber);
            pst.setString(4, email);

            int rowCount = pst.executeUpdate();
            if (rowCount > 0) {
                JOptionPane.showMessageDialog(this, "Booking added successfully");
                clearTable();
                setTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add booking");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
     // Method to delete a booking
    public void deleteBooking() {
        String bookingId = booking_idTx.getText();

        try (Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("DELETE FROM Booking WHERE booking_id = ?")) {

            pst.setString(1, bookingId);

            int rowCount = pst.executeUpdate();
            if (rowCount > 0) {
                JOptionPane.showMessageDialog(this, "Booking deleted successfully");
                clearTable();
                setTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete booking");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) packageTbl.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberTx = new rojerusan.RSMetroTextPlaceHolder();
        slotsTx = new rojerusan.RSMetroTextPlaceHolder();
        booking_idTx = new rojerusan.RSMetroTextPlaceHolder();
        eventTx = new rojerusan.RSMetroTextPlaceHolder();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emailTX = new rojerusan.RSMetroTextPlaceHolder();
        jScrollPane2 = new javax.swing.JScrollPane();
        packageTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numberTx.setBackground(new java.awt.Color(255, 204, 0));
        numberTx.setForeground(new java.awt.Color(0, 0, 0));
        numberTx.setBorderColor(new java.awt.Color(0, 204, 204));
        numberTx.setBotonColor(new java.awt.Color(0, 204, 204));
        numberTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numberTx.setPlaceholder("phone_number");
        numberTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTxActionPerformed(evt);
            }
        });
        getContentPane().add(numberTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, 40));

        slotsTx.setBackground(new java.awt.Color(255, 204, 0));
        slotsTx.setForeground(new java.awt.Color(0, 0, 0));
        slotsTx.setBorderColor(new java.awt.Color(0, 204, 204));
        slotsTx.setBotonColor(new java.awt.Color(0, 204, 204));
        slotsTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slotsTx.setPlaceholder("number_of_slots");
        slotsTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotsTxActionPerformed(evt);
            }
        });
        getContentPane().add(slotsTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 140, 40));

        booking_idTx.setBackground(new java.awt.Color(255, 204, 0));
        booking_idTx.setForeground(new java.awt.Color(0, 0, 0));
        booking_idTx.setBorderColor(new java.awt.Color(0, 204, 204));
        booking_idTx.setBotonColor(new java.awt.Color(0, 204, 204));
        booking_idTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        booking_idTx.setPlaceholder("Booking id");
        booking_idTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking_idTxActionPerformed(evt);
            }
        });
        getContentPane().add(booking_idTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 40));

        eventTx.setBackground(new java.awt.Color(255, 204, 0));
        eventTx.setForeground(new java.awt.Color(0, 0, 0));
        eventTx.setBorderColor(new java.awt.Color(0, 204, 204));
        eventTx.setBotonColor(new java.awt.Color(0, 204, 204));
        eventTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventTx.setPlaceholder("Event");
        eventTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventTxActionPerformed(evt);
            }
        });
        getContentPane().add(eventTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 40));

        jLabel2.setText("Booking id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 90, 10));

        jLabel3.setText("event");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 10));

        jLabel4.setText("number_of_slots");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 10));

        jLabel5.setText("phone_number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 10));

        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, 10));

        emailTX.setBackground(new java.awt.Color(255, 204, 0));
        emailTX.setForeground(new java.awt.Color(0, 0, 0));
        emailTX.setBorderColor(new java.awt.Color(0, 204, 204));
        emailTX.setBotonColor(new java.awt.Color(0, 204, 204));
        emailTX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTX.setPlaceholder("email");
        emailTX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTXActionPerformed(evt);
            }
        });
        getContentPane().add(emailTX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 140, 40));

        packageTbl.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        packageTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking Id", "event", "No_of_slots", "Phone Number", "Email", "Status"
            }
        ));
        packageTbl.setGridColor(new java.awt.Color(0, 204, 204));
        packageTbl.setRowHeight(30);
        packageTbl.setShowGrid(true);
        packageTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                packageTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(packageTbl);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 560, 260));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        delete.setText("delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 20, 20));

        setSize(new java.awt.Dimension(702, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void booking_idTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_idTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booking_idTxActionPerformed

    private void numberTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTxActionPerformed

    private void emailTXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTXActionPerformed

    private void slotsTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotsTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slotsTxActionPerformed

    private void packageTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_packageTblMouseClicked

        int rowNo = packageTbl.getSelectedRow();
        TableModel model = packageTbl.getModel();

        booking_idTx.setText(model.getValueAt(rowNo, 0).toString());
        eventTx.setText(model.getValueAt(rowNo, 1).toString());
        slotsTx.setText(model.getValueAt(rowNo, 2).toString());
        numberTx.setText(model.getValueAt(rowNo, 3).toString());
        emailTX.setText(model.getValueAt(rowNo, 4).toString());

    }//GEN-LAST:event_packageTblMouseClicked

    private void eventTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventTxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addBooking();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        deleteBooking();
    }//GEN-LAST:event_deleteActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMetroTextPlaceHolder booking_idTx;
    private javax.swing.JButton delete;
    private rojerusan.RSMetroTextPlaceHolder emailTX;
    private rojerusan.RSMetroTextPlaceHolder eventTx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSMetroTextPlaceHolder numberTx;
    private javax.swing.JTable packageTbl;
    private rojerusan.RSMetroTextPlaceHolder slotsTx;
    // End of variables declaration//GEN-END:variables
}
