import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class CancelBook extends javax.swing.JFrame {

    /**
     * Creates new form CancelBook
     */
    public CancelBook() {
        initComponents();
    }
    
    public void CancelBooking(){
        String phoneNumber = phoneTx.getText();
        
        // Check if the phone number is not empty and contains only digits
        if (phoneNumber.isEmpty() || !phoneNumber.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Please enter a valid phone number.");
        
    }
        int phone1 = Integer.parseInt(phoneNumber);
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "UPDATE booking SET status = 'Cancelled' WHERE phone_number = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, phone1);
            int rowCount = pst.executeUpdate();
            
            if (rowCount > 0) {
            JOptionPane.showMessageDialog(this, "booking cancelled");
        } else {
            JOptionPane.showMessageDialog(this, "No. not found!");
        }
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        phoneTx = new rojerusan.RSMetroTextPlaceHolder();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Phone Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 20));

        phoneTx.setBackground(new java.awt.Color(255, 204, 0));
        phoneTx.setForeground(new java.awt.Color(0, 0, 0));
        phoneTx.setBorderColor(new java.awt.Color(0, 204, 204));
        phoneTx.setBotonColor(new java.awt.Color(0, 204, 204));
        phoneTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneTx.setPlaceholder("Phone Number");
        phoneTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTxActionPerformed(evt);
            }
        });
        getContentPane().add(phoneTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cancel Booking");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 30));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        setSize(new java.awt.Dimension(431, 246));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTxActionPerformed
        CancelBooking();
    }//GEN-LAST:event_phoneTxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CancelBooking();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private rojerusan.RSMetroTextPlaceHolder phoneTx;
    // End of variables declaration//GEN-END:variables
}
