
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class NewEvent extends javax.swing.JFrame {

    /**
     * Creates new form NewEvent
     */
    public NewEvent() {
        initComponents();
    }
    String eventName;
    String location;
    int days;
    int cost;

       public boolean newEvent(){
        boolean isUpdated = false;
        eventName = eventTx.getText();
        location = locationTx.getText();
        days = Integer.parseInt(daysTx.getText());
        cost = Integer.parseInt(costTx.getText());
        Date uDate = dateTx.getDate();
        
        long l1 = uDate.getTime();
        //convert java.until Date to Java.sql date
        java.sql.Date sqlDate = new java.sql.Date(l1);

        
        
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "INSERT INTO tour_package (package_Name, location, N_days, cost, date) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
                pst.setString(1,eventName);
                pst.setString(2, location);
                pst.setInt(3, days);
                pst.setInt(4, cost);
                pst.setDate(5,sqlDate);
                
            int rowCount = pst.executeUpdate();
            if (rowCount > 0) {
                isUpdated = true;
            }else {
                isUpdated = false;
            }
        
    }catch (Exception e){
        e.printStackTrace();    
    }
    return isUpdated;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        locationTx = new rojerusan.RSMetroTextPlaceHolder();
        daysTx = new rojerusan.RSMetroTextPlaceHolder();
        costTx = new rojerusan.RSMetroTextPlaceHolder();
        eventTx = new rojerusan.RSMetroTextPlaceHolder();
        dateTx = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Event Location");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Add Event");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 30));

        jLabel3.setText("Event Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("Cost");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel5.setText("No of Days");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setText("Select Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        locationTx.setBackground(new java.awt.Color(255, 204, 0));
        locationTx.setForeground(new java.awt.Color(0, 0, 0));
        locationTx.setBorderColor(new java.awt.Color(0, 204, 204));
        locationTx.setBotonColor(new java.awt.Color(0, 204, 204));
        locationTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        locationTx.setPlaceholder("enter location");
        locationTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTxActionPerformed(evt);
            }
        });
        getContentPane().add(locationTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 340, 50));

        daysTx.setBackground(new java.awt.Color(255, 204, 0));
        daysTx.setForeground(new java.awt.Color(0, 0, 0));
        daysTx.setBorderColor(new java.awt.Color(0, 204, 204));
        daysTx.setBotonColor(new java.awt.Color(0, 204, 204));
        daysTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        daysTx.setPlaceholder("No of days");
        daysTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daysTxActionPerformed(evt);
            }
        });
        getContentPane().add(daysTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 340, 50));

        costTx.setBackground(new java.awt.Color(255, 204, 0));
        costTx.setForeground(new java.awt.Color(0, 0, 0));
        costTx.setBorderColor(new java.awt.Color(0, 204, 204));
        costTx.setBotonColor(new java.awt.Color(0, 204, 204));
        costTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        costTx.setPlaceholder("enter amount per person");
        costTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costTxActionPerformed(evt);
            }
        });
        getContentPane().add(costTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 340, 50));

        eventTx.setBackground(new java.awt.Color(255, 204, 0));
        eventTx.setForeground(new java.awt.Color(0, 0, 0));
        eventTx.setBorderColor(new java.awt.Color(0, 204, 204));
        eventTx.setBotonColor(new java.awt.Color(0, 204, 204));
        eventTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventTx.setPlaceholder("Event Name");
        eventTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventTxActionPerformed(evt);
            }
        });
        getContentPane().add(eventTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 340, 50));
        getContentPane().add(dateTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, 40));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 20, 20));

        setSize(new java.awt.Dimension(572, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void locationTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTxActionPerformed

    private void daysTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daysTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daysTxActionPerformed

    private void costTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costTxActionPerformed

    private void eventTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventTxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (newEvent()== true){
        JOptionPane.showMessageDialog(this, "New event added");
        
        }
        else{
             JOptionPane.showMessageDialog(this, "addition failure!");
                        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMetroTextPlaceHolder costTx;
    private com.toedter.calendar.JDateChooser dateTx;
    private rojerusan.RSMetroTextPlaceHolder daysTx;
    private rojerusan.RSMetroTextPlaceHolder eventTx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private rojerusan.RSMetroTextPlaceHolder locationTx;
    // End of variables declaration//GEN-END:variables
}
