
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class SlotsManager extends javax.swing.JFrame {

    /**
     * Creates new form SlotsManager
     */
    public SlotsManager() {
        initComponents();
        setTable();
    }
            DefaultTableModel model;

    public void setTable() {
        
        try (Connection con = DBConnection.getConnection();
             PreparedStatement pst = con.prepareStatement("SELECT package_name, slots FROM tour_package");
             ResultSet rs = pst.executeQuery()) {
            
            while (rs.next()) {
                String package_name = rs.getString("package_name");
                int slots = rs.getInt("slots");
                

                 Object[] obj = {package_name, slots};
                model = (DefaultTableModel)slotsTbl.getModel();
                model.addRow(obj); 
            
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void bookedSlots(){
    String event = eventTx.getText();
    int totalSlots = 0;
    
    try {
        Connection con = DBConnection.getConnection();
        String sql = "SELECT SUM(number_of_slots) AS total_slots FROM booking WHERE event = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        
        pst.setString(1, event);
        
        ResultSet rs = pst.executeQuery();
        if(rs.next()) {
            totalSlots = rs.getInt("total_slots");
        }
        
        jLabel12.setText(String.valueOf(totalSlots));
        
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        slotsTbl = new javax.swing.JTable();
        slotsTx = new rojerusan.RSMetroTextPlaceHolder();
        eventTx = new rojerusan.RSMetroTextPlaceHolder();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "All slots"
            }
        ));
        slotsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slotsTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(slotsTbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 20, 430, 180));

        slotsTx.setBackground(new java.awt.Color(255, 204, 0));
        slotsTx.setForeground(new java.awt.Color(0, 0, 0));
        slotsTx.setBorderColor(new java.awt.Color(0, 204, 204));
        slotsTx.setBotonColor(new java.awt.Color(0, 204, 204));
        slotsTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        slotsTx.setPlaceholder("number_of_slots");
        slotsTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slotsTxActionPerformed(evt);
            }
        });
        getContentPane().add(slotsTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 170, 40));

        eventTx.setBackground(new java.awt.Color(255, 204, 0));
        eventTx.setForeground(new java.awt.Color(0, 0, 0));
        eventTx.setBorderColor(new java.awt.Color(0, 204, 204));
        eventTx.setBotonColor(new java.awt.Color(0, 204, 204));
        eventTx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eventTx.setPlaceholder("Event");
        eventTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventTxActionPerformed(evt);
            }
        });
        getContentPane().add(eventTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 40));

        jLabel3.setText("event");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, -1));

        jLabel4.setText("Booked slots");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, 20));

        jButton1.setText("Check Booked Slots");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 30));

        jPanel14.setBackground(new java.awt.Color(153, 255, 153));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("  booked");
        jPanel14.add(jLabel12);

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 110, 40));

        jLabel5.setText("Total slots");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 90, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 20, 20));

        setSize(new java.awt.Dimension(436, 352));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void slotsTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slotsTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slotsTxActionPerformed

    private void eventTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventTxActionPerformed
       
    }//GEN-LAST:event_eventTxActionPerformed

    private void slotsTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slotsTblMouseClicked
        int rowNo = slotsTbl.getSelectedRow();
        TableModel model = slotsTbl.getModel();

        eventTx.setText(model.getValueAt(rowNo, 0).toString());
        slotsTx.setText(model.getValueAt(rowNo, 1).toString());
        
    }//GEN-LAST:event_slotsTblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bookedSlots();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlotsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlotsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlotsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlotsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotsManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMetroTextPlaceHolder eventTx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable slotsTbl;
    private rojerusan.RSMetroTextPlaceHolder slotsTx;
    // End of variables declaration//GEN-END:variables
}
